### ISSUE TITLE
npm ERR! Failed at the facer@1.0.0 api script 'cross-env NODE_ENV=development node api/start.js'

### ISSUE THREAD

**Issue by officialpm** [gjovanov/facer#1]
[root@localhost facer]# npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.0.6 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN eslint-plugin-vue@4.7.1 requires a peer of eslint@^3.18.0 || ^4.0.0 but none was installed.
[root@localhost facer]#  npm run api

> facer@1.0.0 api /root/facer
> cross-env NODE_ENV=development node api/start.js

/root/facer/api/controller/user-controller.js:95
userRoutes.post("/delete", async(req, res) => {
                                ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/facer/api/index.js:30:24)

npm ERR! Linux 3.10.0-693.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "api"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! facer@1.0.0 api: `cross-env NODE_ENV=development node api/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the facer@1.0.0 api script 'cross-env NODE_ENV=development node api/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the facer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node api/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs facer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls facer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/facer/npm-debug.log

**Comment by officialpm** [comment]
Using Cent OS 7

**Comment by officialpm** [comment]
SOLVED IT ! used Ubuntu ! SORRY YOU CAN DELETE THIS STUPID ISSUE
